### PR TITLE
Clientside joins

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This pull request adds:

New parameter to bokehDrawArray - sourceArray

Outside of specifying histograms as in histoArray, it also allows specifying secondary data sources and joins on the client

Do not merge yet, case when histograms use sources different from primary CDS is broken, taking variables from secondary sources derived on server doesn't work either.

Use case:
```
df2 = pd.DataFrame(...)
sourceArray = [
  {"name": "df2", "data": df2},
  {"name": "join_df2", "left": None, "right":"df2", "left_on": ["bin_index"], "right_on": ["bin_index"], "how": "left"}
]
```

### CODE REVIEW

**Comment by miranov25** [comment]
# Comment concerning unit test on client:
Unit test based on the check of in-variances on client should be implemented as a next steps
For the moment we will check content manually but in next pull request check of in-variances has to be added

**Comment by miranov25** [comment]
### Test on tensorflow singularity container at GSI is OK:
===================================================================== 34 passed, 1 skipped, 2 warnings in 232.53s (0:03:52) ======================================================================

### Test on Ubuntu/laptop   is OK
===================================================================== 34 passed, 1 skipped, 2 warnings in 168.86s (0:02:48) ======================================================================

**Comment by miranov25** [comment]
### Check of the tutorial:
* http://127.0.0.1:8888/notebooks/RootInteractive/tutorial/bokehDraw/customJsColumns.ipynb
  * not failing
* http://127.0.0.1:8888/notebooks/RootInteractive/tutorial/bokehDraw/standAlone.ipynb
  *  not failing
* http://127.0.0.1:8888/notebooks/RootInteractive/tutorial/bokehDraw/test_bokehClientHistogram.ipynb
** not failing

**Comment by miranov25** [comment]
Merging

**Comment by pl0xz0rz** [comment]
Also should fix #174

**Pull request merged**
