### PR TITLE
Changes in makeHistogram and makePdfMaps functions

### PR DESCRIPTION
**Pull request by ehellbar**
Hello Marian, Marian, Martin and Alperen,
in this draft pull request I would like to show you the modifications I did to get this functionality to work for the space-charge calibration studies.

1) In the makeHistogram function, I tried to compactify the data frame usage to avoid as many copies as possible. This gets relevant when working with big data frames. If you have further ideas on how to optimize the code for memory usage or compress the objects, please let me know.

2) I applied a quick fix in the makePdfMaps function. It avoids errors when the bins to fit are empty, setting means, rms and meansOK flag to 0. Something similar is done for medians and quantiles when the last bin in the loop is reached. However, here probably some values different from 0 could be set but I did not look into the calculations yet.

Cheers,
Ernst

### CODE REVIEW

**Comment by miranov25** [comment]
I think I understand your changes.
Can we meet on Vidyo to Review together

**Comment by ehellbar** [comment]
Hello Marian,
I have a meeting at 10. Can we meet at 11:30?

**Comment by ehellbar** [comment]
* Changing status from draft PR to PR

**Comment by miranov25** [comment]
## Observed improvements histoNDTools.py (Ernst)
do not cache results of panda queries (rough value)
* Input TTree 800 MBy
* Panda 4 GBy
* Before modification:
  * histograms  creation before modification ->11 GBy
  * saving using pickle -> 15 GBy
* After modification:
  * histograms  creation before modification ->8 GBy
  * saving using pickle -> 12 GBy

**Comment by miranov25** [comment]
## Tools/makePDFMaps.py 
* Observed time to make PDF map from histogram ~ 5 minutes (180 x 33 x 40 x 8 )
* time to be compared with the C++ implementation 
* to be further optimized = we need time profile

**Pull request merged**
