### PR TITLE
Predict rf stat

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR:
-Makes multiselect widget work with new pandas
-Removes one liner utility functions from #320, performance of predictRFStat improved by further 10%

### CODE REVIEW

**Comment by miranov25** [comment]
Did we have an issue created for the categorical multi-select pandas?
* if yes -can you add it?
* if not can you describe what you actually did?

**Comment by miranov25** [comment]
Checking source code changes for categorical - is it related only to the output table, so it is only new feature?

**Comment by miranov25** [comment]
We forgot to merge this request. Is this code compatible with the LinearRegression pull request?

**Comment by pl0xz0rz** [comment]
No, but manually merging it shouldn't be an issue, the only merge conflict should be a single line in the makeBokehMultiSelectSlider

**Comment by miranov25** [comment]
Fixed as side change in pull request  #325

**Pull request closed without merging**
