### PR TITLE
Histogram ranges / number of bins widgets

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR:
- Allows modifying histogram ranges and number of bins on the client using parameterArray
- Fixes a bug with ND histogram where it wasn't updating the length correctly (as the length was never updated in any use case, the bug wasn't really a bug before the nbins parameter was added)
- Fixes a bug in the downsampler with changing input sizes (before this change, it was an edge case, this change made it visible)
- Slightly optimizes the dependency tree by not adding the pre-transformation multiSelect columns
- in test_bokehClientHistogram.py fixes the output file name for test_bokehClientHistogram3d
- Fixes a bug caused in #172 causing widgetArray to sometimes get modified in place
   - was there   since Nov 20, 2021, but this fragment of code not used until text input for selection

Relates to #218

### CODE REVIEW

**Comment by pl0xz0rz** [comment]
Also when making this pull request, I have noticed that you can also specify nPointRender with either a slider or a select (range has to be specified for slider, options for select)

**Comment by miranov25** [comment]
Thank you for the changes.
Parameter nPointRender we are already using in our real use cases and I think should be also in the tutorial. 
It is already in the template - bokehInteractiveParameters.py

* https://github.com/miranov25/RootInteractive/blob/2250c2c6a654e0dd4136143fc85273d169a1f37c/RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveParameters.py#L42-L53

**Comment by miranov25** [comment]
Tests look fine at GSI node - except for the usual suspect with tree (we should fix it later)
```
========================================================================================= short test summary info ==========================================================================================
FAILED test_bokehDrawSA.py::testBokehDrawArraySA_tree - TypeError: can only concatenate list (not "str") to list
=========================================================================== 1 failed, 36 passed, 7 warnings in 143.48s (0:02:23) ===========================================================================
```

**Comment by miranov25** [comment]
The ND-histogram looks to not react to change of binning   ... to be fixed

**Comment by miranov25** [comment]
in ranges and nbins not used in the test to be added:
file:///u/miranov/github/RootInteractive/RootInteractive/InteractiveDrawing/bokeh/test_BokehClientHistogram3d.html
I test also the figure height should be reduced - to properly scale.

**Comment by miranov25** [comment]
- Histogram tests were OK.
- all draw tests except one are OK
- merging

```
========================================================================================= short test summary info ==========================================================================================
FAILED test_bokehDrawSA.py::testBokehDrawArraySA_tree - TypeError: can only concatenate list (not "str") to list
=========================================================================== 1 failed, 36 passed, 7 warnings in 339.27s (0:05:39) ===========================================================================
```

**Pull request merged**
