### PR TITLE
Update keras to tensorflow.keras for tenserflow>=2.5.0

### PR DESCRIPTION
**Pull request by ehellbar**

### CODE REVIEW

**Comment by ehellbar** [comment]
Hello @miranov25 ,
please do not merge yet, I think further modifications are required to make this work.

**Comment by ehellbar** [comment]
This PR should work fine but to me it seems like the KerasModel is implemented differently than the others. For RF for example, the fitting is done with the fitter in line 684 of RootInteractive/MLpipeline/NDFunctionInterface.py. For the KerasModel, there is no dedicated Fit function in RootInteractive, instead it is fitted in the init function. This produces error when registering the KerasModel to the fitter and executing the Fit.

`
AttributeError                            Traceback (most recent call last)
<ipython-input-12-4f5e9ca94917> in <module>
      9 # fitter.Register_Method('RF200','RandomForest', 'Regressor', n_estimators=200, max_depth=10)
     10 fitter.Register_Method('KM','KerasModel', 'Regressor', layout = [50, 50, 50], epochs=300, dropout=0.4)
---> 11 fitter.Fit()
     12 test=dataContainer.Test_sample
     13 #fitter.Compress('KM')

/lustre/alice/users/hellbaer/RootInteractive/RootInteractive/MLpipeline/NDFunctionInterface.py in Fit(self)
    682             else:
    683                 return
--> 684             MDL.fit(self.data.X_train, np.ravel(self.data.y_train))
    685             MDL.model_name=self.method_name[idx]
    686             self.Models.append(MDL)

AttributeError: 'KerasModel' object has no attribute 'fit'
`

**Comment by ehellbar** [comment]
Please bare in mind that approving this change might require to update singularity containers to tensorflow>=2.5

**Comment by miranov25** [comment]
Hello Ernst.
We prepare new pull request for ND histogramming on client
Once it is done, we will proceed with your pull request.

**Pull request closed without merging**
