### PR TITLE
Client side functions and efficiencies

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR adds support for custom JS functions in bokehDrawArray computed on the client either on the histograms or the main CDS.

### CODE REVIEW

**Comment by miranov25** [comment]
Thanks for pull request
I will run the test with our real use cases. I would like to ask you to add Jupyter notebook with the tutorial. Like you did last time for histograms, sing unit test example which you already wrote.

**Comment by miranov25** [comment]
relates to the issue #155

**Comment by miranov25** [comment]
## Checking test test_bokehDrawSA.py current -> new

we should invent automatic test - writing report on client - CPU time  for the jscallback such that we can compare perfromance autmatically qualitatively


test_BokehDrawArrayDownsample.html - speed 30 ms ~ 80 ms 
/test_BokehDrawArrayWidget.html  - similar speed 94-100 ms for CD update
test_BokehDrawArrayQuery.html  - looks strange (both in current master and update) - too few points selected 
problem in the automatic range for the variable C in the test

**Comment by miranov25** [comment]
h2. testing global options

* problem with the global option (recently introduced) was solved by commits above
* documentation of the global options should be in tutorial
Real use case works after https://github.com/miranov25/RootInteractive/pull/166/commits/486c4d8b659d0a28b1660552b12c4c02ed8cbeb2

**Comment by miranov25** [comment]
Tutorial standAlone.ipynb  is failing, looks like @pl0xz0rz did not commit last working version
could you please also comment the notebook with markdown once you fix it?

**Comment by miranov25** [comment]
@pl0xz0rz, I am checking test again - looks like the  bug in histograms is not the bug on the code but in my expectation ...
most the axes are fine ....

**Comment by pl0xz0rz** [comment]
Fixes #164

**Pull request merged**
