### PR TITLE
PWGPP-581 N-dimensional histogramming benchmark

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR adds benchmarking code to the PyTorch N-dimensional histogramming tool. This is the file of the benchmark output on my machine. Times are in ms per one histogram.

### Uniform binning: 
Numpy: 
|    |     1e2 |     1e3 |     1e4 |     1e5 |     1e6 |     1e7 |
|----|---------|---------|---------|---------|---------|---------|
|  3 |  0.2095 |  0.3139 |  1.3679 | 11.4454 | 157.021 | 1960.69 |
|  4 |  0.3308 |  0.4531 |  1.8226 | 16.9595 | 219.219 | 2662.92 |
|  5 |  3.1293 |  3.2811 |  4.9445 | 24.8206 | 286.331 | 3574.78 |
|  6 | 34.408  | 34.6864 | 37.1484 | 61.7969 | 472.131 | 4551.02 |

PyTorch CPU: 
|    |    1e2 |     1e3 |    1e4 |     1e5 |      1e6 |      1e7 |
|----|--------|---------|--------|---------|----------|----------|
|  3 | 0.5915 |  0.6447 | 1.0245 |  7.629  |  57.9476 |  643.39  |
|  4 | 0.6751 |  0.7211 | 1.0178 |  7.3699 |  71.5828 |  895.599 |
|  5 | 1.6042 |  1.3475 | 1.7276 |  9.6214 | 133.742  | 1133.72  |
|  6 | 8.4555 | 11.9247 | 9.3707 | 19.098  | 148.791  | 1616.52  |

PyTorch CUDA: 
|    |    1e2 |    1e3 |    1e4 |    1e5 |     1e6 |     1e7 |
|----|--------|--------|--------|--------|---------|---------|
|  3 | 3.1708 | 3.2489 | 3.175  | 4.6245 | 15.231  | 122.855 |
|  4 | 3.7462 | 3.6169 | 3.6932 | 4.9276 | 16.779  | 136.683 |
|  5 | 4.2622 | 4.1095 | 4.1405 | 5.6287 | 20.4805 | 163.636 |
|  6 | 5.212  | 5.4013 | 5.5737 | 7.7179 | 29.4644 | 235.449 |

### Custom binning: 
Numpy: 
|    |     1e2 |     1e3 |     1e4 |     1e5 |     1e6 |     1e7 |
|----|---------|---------|---------|---------|---------|---------|
|  3 |  0.0942 |  0.1923 |  1.1195 | 10.3695 | 144.948 | 1840.42 |
|  4 |  0.1462 |  0.2816 |  1.5403 | 13.8997 | 198.91  | 2469.55 |
|  5 |  3.0384 |  3.1955 |  4.642  | 21.0965 | 255.263 | 3154.92 |
|  6 | 34.4577 | 35.5735 | 37.1265 | 58.566  | 422.356 | 3956.98 |

PyTorch CPU: 
|    |     1e2 |    1e3 |    1e4 |     1e5 |      1e6 |      1e7 |
|----|---------|--------|--------|---------|----------|----------|
|  3 |  0.3433 | 0.3851 | 1.1735 |  6.4706 |  67.2968 |  853.978 |
|  4 |  0.4135 | 0.4551 | 0.9737 |  9.0621 |  90.2246 | 1217.1   |
|  5 |  1.29   | 1.4303 | 1.7511 | 11.7872 | 108.467  | 1538.12  |
|  6 | 10.2312 | 7.6337 | 9.1426 | 22.4487 | 196.138  | 1948.4   |

PyTorch CUDA: 
|    |    1e2 |    1e3 |    1e4 |    1e5 |     1e6 |      1e7 |
|----|--------|--------|--------|--------|---------|----------|
|  3 | 1.4808 | 1.4575 | 1.5768 | 2.4007 | 10.5617 |  89.3735 |
|  4 | 1.5851 | 1.5787 | 1.6688 | 2.5035 | 11.0659 |  92.0011 |
|  5 | 1.8847 | 1.8446 | 1.8306 | 2.8386 | 12.6494 | 108.204  |
|  6 | 2.7251 | 2.6371 | 2.7562 | 4.2877 | 20.7345 | 168.842  |

### CODE REVIEW

**Comment by miranov25** [comment]
Thanks
I checked tables. Cuda and cpu is exactly the same
Could you crosscheck?

**Comment by pl0xz0rz** [comment]
Fixed the bug causing that - it was caused by a typo, the tables should look more correct now.

**Comment by miranov25** [comment]
Putting link to the presentation:
https://docs.google.com/presentation/d/1vYPTTsn5Zs7X9OWaewUTlnw9hqJ3XKJNGKiAViHv-cY/edit?usp=sharing

**Comment by miranov25** [comment]
## Benchmark results on computer with 128 cores

### Uniform binning: 
Numpy: 
|    |      1e2 |       1e3 |      1e4 |      1e5 |     1e6 |     1e7 |
|----|----------|-----------|----------|----------|---------|---------|
|  3 | 0.377415 |  0.47393  |  1.33688 |  9.81691 | 127.781 | 1075.23 |
|  4 | 0.514168 |  0.639238 |  1.79037 | 13.1806  | 149.903 | 1465.27 |
|  5 | 0.972468 |  1.1308   |  2.59268 | 17.1995  | 191.152 | 1885.31 |
|  6 | 9.43532  | 10.4809   | 13.4918  | 33.0809  | 251.536 | 2375.37 |

PyTorch CPU: 
|    |      1e2 |      1e3 |      1e4 |     1e5 |     1e6 |     1e7 |
|----|----------|----------|----------|---------|---------|---------|
|  3 | 0.510511 | 0.530569 | 0.706787 | 2.60794 | 12.3819 | 241.604 |
|  4 | 0.544486 | 0.567881 | 1.41121  | 2.73473 | 20.0818 | 297.408 |
|  5 | 0.862657 | 0.924005 | 1.59521  | 3.46787 | 34.1355 | 362.626 |
|  6 | 0.912854 | 0.984471 | 1.87706  | 4.89862 | 42.8083 | 441.325 |

### Custom binning: 
Numpy: 
|    |      1e2 |       1e3 |      1e4 |      1e5 |      1e6 |      1e7 |
|----|----------|-----------|----------|----------|----------|----------|
|  3 | 0.173543 |  0.258306 |  1.05542 |  8.98816 |  99.8069 |  985.642 |
|  4 | 0.240401 |  0.353689 |  1.4157  | 12.0554  | 145.477  | 1325.17  |
|  5 | 0.631333 |  0.773866 |  2.11908 | 15.8033  | 168.836  | 1682.09  |
|  6 | 8.9848   | 10.0029   | 12.6798  | 31.3145  | 241.425  | 2099.02  |

PyTorch CPU: 
|    |      1e2 |      1e3 |      1e4 |     1e5 |      1e6 |     1e7 |
|----|----------|----------|----------|---------|----------|---------|
|  3 | 1.19737  | 0.423975 | 0.67174  | 1.51322 |  7.52757 | 154.125 |
|  4 | 0.444754 | 0.465474 | 0.940116 | 2.034   | 12.4905  | 187.952 |
|  5 | 0.520529 | 0.582178 | 1.12672  | 2.53665 | 27.8552  | 227.839 |
|  6 | 0.576076 | 0.650229 | 1.21995  | 3.57586 | 37.7834  | 300.145 |

**Comment by miranov25** [comment]
## Benchmark results 
* Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

### Uniform binning: 
Numpy: 
|    |       1e2 |       1e3 |       1e4 |      1e5 |     1e6 |      1e7 |
|----|-----------|-----------|-----------|----------|---------|----------|
|  3 |  0.165241 |  0.248625 |  0.906176 |  7.17047 |  84.814 |  973.908 |
|  4 |  0.229474 |  0.344372 |  1.21336  |  9.77649 | 109.375 | 1355.44  |
|  5 |  0.61687  |  0.802965 |  1.79547  | 13.0421  | 155.459 | 1770.89  |
|  6 | 14.5507   | 13.8311   | 16.3262   | 27.6864  | 214.572 | 2324.63  |

PyTorch CPU: 
|    |      1e2 |      1e3 |      1e4 |     1e5 |     1e6 |     1e7 |
|----|----------|----------|----------|---------|---------|---------|
|  3 | 0.337424 | 0.352994 | 0.507932 | 1.50428 | 18.1363 | 214.445 |
|  4 | 0.400804 | 0.386108 | 0.655715 | 2.00001 | 24.8    | 281.784 |
|  5 | 0.458024 | 0.501923 | 0.813008 | 2.60847 | 34.2185 | 335.936 |
|  6 | 1.9818   | 2.10419  | 2.47908  | 5.83185 | 45.4191 | 444.569 |

### Custom binning: 
Numpy: 
|    |       1e2 |       1e3 |       1e4 |      1e5 |      1e6 |      1e7 |
|----|-----------|-----------|-----------|----------|----------|----------|
|  3 |  0.084459 |  0.156706 |  0.741777 |  6.55782 |  80.9501 |  902.204 |
|  4 |  0.125837 |  0.228421 |  1.00264  |  8.92457 | 106.061  | 1197.36  |
|  5 |  1.26003  |  0.560729 |  1.51911  | 11.7989  | 124.856  | 1592.46  |
|  6 | 13.7425   | 13.9933   | 15.3441   | 27.887   | 196.687  | 1982.81  |

PyTorch CPU: 
|    |      1e2 |      1e3 |      1e4 |     1e5 |     1e6 |     1e7 |
|----|----------|----------|----------|---------|---------|---------|
|  3 | 0.211795 | 0.228805 | 0.455242 | 2.5503  | 28.4213 | 364.143 |
|  4 | 0.240558 | 0.286336 | 0.598203 | 3.37673 | 37.0912 | 484.482 |
|  5 | 0.273545 | 0.330448 | 0.748071 | 4.34222 | 51.444  | 531.796 |
|  6 | 1.79449  | 1.78565  | 2.38616  | 7.66311 | 66.5588 | 677.762 |

**Pull request merged**
