### PR TITLE
Custom JS function text input

### LINKED ISSUE #229: Custom user JS function text input
# Goal:
Implementation of the custom user functions using text input.

Example usage

customCut 
return ITSOn & Math.abs(dcaXY)<4

### PR DESCRIPTION
**Pull request by pl0xz0rz**
This PR:
-Adds a test for custom JS function text input - test_Alias.py
-Fixes bugs preventing it from working - seems that for some reason, it was already mostly implemented, and the only changes needed were fixing a broken 2-line JS callback, and creating the text input widget itself.
Fixes #229 

How to use:
In widget array, create a "text" widget, where the relevant argument is parameter name
```
aliasArray=[
    {
        "name": "custom_column",
        "variables": ["A", "B", "C", "A_mul_paramX_plus_B"],
        "func": "CustomFunc"
    }
]
parameterArray=[
    {"name": "CustomFunc", "value":"return Math.sin(A_mul_paramX_plus_B)"}
]
widgetParams=[
   ...,
    ['text', ["CustomFunc"]],
   ....
]
```

Screenshot of result:
Capture

### CODE REVIEW

**Comment by miranov25** [comment]
This pull request should finish the implementation of the issue #229

**Comment by miranov25** [comment]
Example usage of new functionality in the UnitTest:
sin(2*pi*A)
image

**Comment by miranov25** [comment]
Hello @pl0xz0rz 

Could you edit the pull request and refer to issue #229 and to previous

**Comment by miranov25** [comment]
I closed by mistake

**Comment by miranov25** [comment]
What is the response in case invalid function?

**Comment by miranov25** [comment]
The test "formally working"
```
========================================================================================= short test summary info ==========================================================================================
FAILED test_bokehDrawSA.py::testBokehDrawArraySA_tree - TypeError: can only concatenate list (not "str") to list
========================================================================== 1 failed, 36 passed, 11 warnings in 509.68s (0:08:29) ===========================================================================
```

**Comment by miranov25** [comment]
Hello @pl0xz0rz 

Looks like there is one feature missing. The text alias does not support the name option.
Therefore it can not be added to the layout via name only via the index. 
i assume there is something missing in text widget implementation. 


`#widgetLayoutHistCut=[["itsNclsCut","tpcNclsCut","trdNclsCut"],["dcaXYCut","dcaZCut"], ["cutCustom","cutCustomRef"], {'sizing_mode': 'scale_width'}] `
-->

`widgetLayoutHistCut=[["itsNclsCut","tpcNclsCut","trdNclsCut"],["dcaXYCut","dcaZCut"], [39,40], {'sizing_mode': 'scale_width'}] `


In the  test_Alias.py you are using index not name. therefore it was not tested 

```
widgetLayoutDesc={
    "Selection": [[0, 1, 2], [3, 4], {'sizing_mode': 'scale_width'}],
    "Graphics": [[5, 6], {'sizing_mode': 'scale_width'}],
    "CustomJS functions": [[7, 8],[9]]
    }
```

**Comment by pl0xz0rz** [comment]
Bug with broken name option fixed, tests for fix added in test_Alias.py and test_bokehDrawSA.py

**Comment by miranov25** [comment]
Fix in above commets fixed the problem with the layout
merging

**Pull request merged**
